<?php
/**
 * CompanyProfile
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Finnhub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Finnhub\Model;

use \ArrayAccess;
use \Finnhub\ObjectSerializer;

/**
 * CompanyProfile Class Doc Comment
 *
 * @category Class
 * @package  Finnhub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class CompanyProfile implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CompanyProfile';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'alias' => 'string[]',
        'address' => 'string',
        'city' => 'string',
        'country' => 'string',
        'currency' => 'string',
        'estimate_currency' => 'string',
        'market_cap_currency' => 'string',
        'cusip' => 'string',
        'sedol' => 'string',
        'description' => 'string',
        'exchange' => 'string',
        'ggroup' => 'string',
        'gind' => 'string',
        'gsector' => 'string',
        'gsubind' => 'string',
        'isin' => 'string',
        'lei' => 'string',
        'naics_national_industry' => 'string',
        'naics' => 'string',
        'naics_sector' => 'string',
        'naics_subsector' => 'string',
        'name' => 'string',
        'phone' => 'string',
        'state' => 'string',
        'ticker' => 'string',
        'weburl' => 'string',
        'ipo' => '\DateTime',
        'market_capitalization' => 'float',
        'share_outstanding' => 'float',
        'employee_total' => 'float',
        'logo' => 'string',
        'finnhub_industry' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'alias' => null,
        'address' => null,
        'city' => null,
        'country' => null,
        'currency' => null,
        'estimate_currency' => null,
        'market_cap_currency' => null,
        'cusip' => null,
        'sedol' => null,
        'description' => null,
        'exchange' => null,
        'ggroup' => null,
        'gind' => null,
        'gsector' => null,
        'gsubind' => null,
        'isin' => null,
        'lei' => null,
        'naics_national_industry' => null,
        'naics' => null,
        'naics_sector' => null,
        'naics_subsector' => null,
        'name' => null,
        'phone' => null,
        'state' => null,
        'ticker' => null,
        'weburl' => null,
        'ipo' => 'date',
        'market_capitalization' => 'float',
        'share_outstanding' => 'float',
        'employee_total' => 'float',
        'logo' => null,
        'finnhub_industry' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'alias' => 'alias',
        'address' => 'address',
        'city' => 'city',
        'country' => 'country',
        'currency' => 'currency',
        'estimate_currency' => 'estimateCurrency',
        'market_cap_currency' => 'marketCapCurrency',
        'cusip' => 'cusip',
        'sedol' => 'sedol',
        'description' => 'description',
        'exchange' => 'exchange',
        'ggroup' => 'ggroup',
        'gind' => 'gind',
        'gsector' => 'gsector',
        'gsubind' => 'gsubind',
        'isin' => 'isin',
        'lei' => 'lei',
        'naics_national_industry' => 'naicsNationalIndustry',
        'naics' => 'naics',
        'naics_sector' => 'naicsSector',
        'naics_subsector' => 'naicsSubsector',
        'name' => 'name',
        'phone' => 'phone',
        'state' => 'state',
        'ticker' => 'ticker',
        'weburl' => 'weburl',
        'ipo' => 'ipo',
        'market_capitalization' => 'marketCapitalization',
        'share_outstanding' => 'shareOutstanding',
        'employee_total' => 'employeeTotal',
        'logo' => 'logo',
        'finnhub_industry' => 'finnhubIndustry'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'alias' => 'setAlias',
        'address' => 'setAddress',
        'city' => 'setCity',
        'country' => 'setCountry',
        'currency' => 'setCurrency',
        'estimate_currency' => 'setEstimateCurrency',
        'market_cap_currency' => 'setMarketCapCurrency',
        'cusip' => 'setCusip',
        'sedol' => 'setSedol',
        'description' => 'setDescription',
        'exchange' => 'setExchange',
        'ggroup' => 'setGgroup',
        'gind' => 'setGind',
        'gsector' => 'setGsector',
        'gsubind' => 'setGsubind',
        'isin' => 'setIsin',
        'lei' => 'setLei',
        'naics_national_industry' => 'setNaicsNationalIndustry',
        'naics' => 'setNaics',
        'naics_sector' => 'setNaicsSector',
        'naics_subsector' => 'setNaicsSubsector',
        'name' => 'setName',
        'phone' => 'setPhone',
        'state' => 'setState',
        'ticker' => 'setTicker',
        'weburl' => 'setWeburl',
        'ipo' => 'setIpo',
        'market_capitalization' => 'setMarketCapitalization',
        'share_outstanding' => 'setShareOutstanding',
        'employee_total' => 'setEmployeeTotal',
        'logo' => 'setLogo',
        'finnhub_industry' => 'setFinnhubIndustry'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'alias' => 'getAlias',
        'address' => 'getAddress',
        'city' => 'getCity',
        'country' => 'getCountry',
        'currency' => 'getCurrency',
        'estimate_currency' => 'getEstimateCurrency',
        'market_cap_currency' => 'getMarketCapCurrency',
        'cusip' => 'getCusip',
        'sedol' => 'getSedol',
        'description' => 'getDescription',
        'exchange' => 'getExchange',
        'ggroup' => 'getGgroup',
        'gind' => 'getGind',
        'gsector' => 'getGsector',
        'gsubind' => 'getGsubind',
        'isin' => 'getIsin',
        'lei' => 'getLei',
        'naics_national_industry' => 'getNaicsNationalIndustry',
        'naics' => 'getNaics',
        'naics_sector' => 'getNaicsSector',
        'naics_subsector' => 'getNaicsSubsector',
        'name' => 'getName',
        'phone' => 'getPhone',
        'state' => 'getState',
        'ticker' => 'getTicker',
        'weburl' => 'getWeburl',
        'ipo' => 'getIpo',
        'market_capitalization' => 'getMarketCapitalization',
        'share_outstanding' => 'getShareOutstanding',
        'employee_total' => 'getEmployeeTotal',
        'logo' => 'getLogo',
        'finnhub_industry' => 'getFinnhubIndustry'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['alias'] = $data['alias'] ?? null;
        $this->container['address'] = $data['address'] ?? null;
        $this->container['city'] = $data['city'] ?? null;
        $this->container['country'] = $data['country'] ?? null;
        $this->container['currency'] = $data['currency'] ?? null;
        $this->container['estimate_currency'] = $data['estimate_currency'] ?? null;
        $this->container['market_cap_currency'] = $data['market_cap_currency'] ?? null;
        $this->container['cusip'] = $data['cusip'] ?? null;
        $this->container['sedol'] = $data['sedol'] ?? null;
        $this->container['description'] = $data['description'] ?? null;
        $this->container['exchange'] = $data['exchange'] ?? null;
        $this->container['ggroup'] = $data['ggroup'] ?? null;
        $this->container['gind'] = $data['gind'] ?? null;
        $this->container['gsector'] = $data['gsector'] ?? null;
        $this->container['gsubind'] = $data['gsubind'] ?? null;
        $this->container['isin'] = $data['isin'] ?? null;
        $this->container['lei'] = $data['lei'] ?? null;
        $this->container['naics_national_industry'] = $data['naics_national_industry'] ?? null;
        $this->container['naics'] = $data['naics'] ?? null;
        $this->container['naics_sector'] = $data['naics_sector'] ?? null;
        $this->container['naics_subsector'] = $data['naics_subsector'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['phone'] = $data['phone'] ?? null;
        $this->container['state'] = $data['state'] ?? null;
        $this->container['ticker'] = $data['ticker'] ?? null;
        $this->container['weburl'] = $data['weburl'] ?? null;
        $this->container['ipo'] = $data['ipo'] ?? null;
        $this->container['market_capitalization'] = $data['market_capitalization'] ?? null;
        $this->container['share_outstanding'] = $data['share_outstanding'] ?? null;
        $this->container['employee_total'] = $data['employee_total'] ?? null;
        $this->container['logo'] = $data['logo'] ?? null;
        $this->container['finnhub_industry'] = $data['finnhub_industry'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets alias
     *
     * @return string[]|null
     */
    public function getAlias()
    {
        return $this->container['alias'];
    }

    /**
     * Sets alias
     *
     * @param string[]|null $alias Company name alias.
     *
     * @return self
     */
    public function setAlias($alias)
    {
        $this->container['alias'] = $alias;

        return $this;
    }

    /**
     * Gets address
     *
     * @return string|null
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string|null $address Address of company's headquarter.
     *
     * @return self
     */
    public function setAddress($address)
    {
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string|null
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string|null $city City of company's headquarter.
     *
     * @return self
     */
    public function setCity($city)
    {
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country Country of company's headquarter.
     *
     * @return self
     */
    public function setCountry($country)
    {
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string|null
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string|null $currency Currency used in company filings and financials.
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets estimate_currency
     *
     * @return string|null
     */
    public function getEstimateCurrency()
    {
        return $this->container['estimate_currency'];
    }

    /**
     * Sets estimate_currency
     *
     * @param string|null $estimate_currency Currency used in Estimates data.
     *
     * @return self
     */
    public function setEstimateCurrency($estimate_currency)
    {
        $this->container['estimate_currency'] = $estimate_currency;

        return $this;
    }

    /**
     * Gets market_cap_currency
     *
     * @return string|null
     */
    public function getMarketCapCurrency()
    {
        return $this->container['market_cap_currency'];
    }

    /**
     * Sets market_cap_currency
     *
     * @param string|null $market_cap_currency Currency used in market capitalization.
     *
     * @return self
     */
    public function setMarketCapCurrency($market_cap_currency)
    {
        $this->container['market_cap_currency'] = $market_cap_currency;

        return $this;
    }

    /**
     * Gets cusip
     *
     * @return string|null
     */
    public function getCusip()
    {
        return $this->container['cusip'];
    }

    /**
     * Sets cusip
     *
     * @param string|null $cusip CUSIP number.
     *
     * @return self
     */
    public function setCusip($cusip)
    {
        $this->container['cusip'] = $cusip;

        return $this;
    }

    /**
     * Gets sedol
     *
     * @return string|null
     */
    public function getSedol()
    {
        return $this->container['sedol'];
    }

    /**
     * Sets sedol
     *
     * @param string|null $sedol Sedol number.
     *
     * @return self
     */
    public function setSedol($sedol)
    {
        $this->container['sedol'] = $sedol;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Company business summary.
     *
     * @return self
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets exchange
     *
     * @return string|null
     */
    public function getExchange()
    {
        return $this->container['exchange'];
    }

    /**
     * Sets exchange
     *
     * @param string|null $exchange Listed exchange.
     *
     * @return self
     */
    public function setExchange($exchange)
    {
        $this->container['exchange'] = $exchange;

        return $this;
    }

    /**
     * Gets ggroup
     *
     * @return string|null
     */
    public function getGgroup()
    {
        return $this->container['ggroup'];
    }

    /**
     * Sets ggroup
     *
     * @param string|null $ggroup Industry group.
     *
     * @return self
     */
    public function setGgroup($ggroup)
    {
        $this->container['ggroup'] = $ggroup;

        return $this;
    }

    /**
     * Gets gind
     *
     * @return string|null
     */
    public function getGind()
    {
        return $this->container['gind'];
    }

    /**
     * Sets gind
     *
     * @param string|null $gind Industry.
     *
     * @return self
     */
    public function setGind($gind)
    {
        $this->container['gind'] = $gind;

        return $this;
    }

    /**
     * Gets gsector
     *
     * @return string|null
     */
    public function getGsector()
    {
        return $this->container['gsector'];
    }

    /**
     * Sets gsector
     *
     * @param string|null $gsector Sector.
     *
     * @return self
     */
    public function setGsector($gsector)
    {
        $this->container['gsector'] = $gsector;

        return $this;
    }

    /**
     * Gets gsubind
     *
     * @return string|null
     */
    public function getGsubind()
    {
        return $this->container['gsubind'];
    }

    /**
     * Sets gsubind
     *
     * @param string|null $gsubind Sub-industry.
     *
     * @return self
     */
    public function setGsubind($gsubind)
    {
        $this->container['gsubind'] = $gsubind;

        return $this;
    }

    /**
     * Gets isin
     *
     * @return string|null
     */
    public function getIsin()
    {
        return $this->container['isin'];
    }

    /**
     * Sets isin
     *
     * @param string|null $isin ISIN number.
     *
     * @return self
     */
    public function setIsin($isin)
    {
        $this->container['isin'] = $isin;

        return $this;
    }

    /**
     * Gets lei
     *
     * @return string|null
     */
    public function getLei()
    {
        return $this->container['lei'];
    }

    /**
     * Sets lei
     *
     * @param string|null $lei LEI number.
     *
     * @return self
     */
    public function setLei($lei)
    {
        $this->container['lei'] = $lei;

        return $this;
    }

    /**
     * Gets naics_national_industry
     *
     * @return string|null
     */
    public function getNaicsNationalIndustry()
    {
        return $this->container['naics_national_industry'];
    }

    /**
     * Sets naics_national_industry
     *
     * @param string|null $naics_national_industry NAICS national industry.
     *
     * @return self
     */
    public function setNaicsNationalIndustry($naics_national_industry)
    {
        $this->container['naics_national_industry'] = $naics_national_industry;

        return $this;
    }

    /**
     * Gets naics
     *
     * @return string|null
     */
    public function getNaics()
    {
        return $this->container['naics'];
    }

    /**
     * Sets naics
     *
     * @param string|null $naics NAICS industry.
     *
     * @return self
     */
    public function setNaics($naics)
    {
        $this->container['naics'] = $naics;

        return $this;
    }

    /**
     * Gets naics_sector
     *
     * @return string|null
     */
    public function getNaicsSector()
    {
        return $this->container['naics_sector'];
    }

    /**
     * Sets naics_sector
     *
     * @param string|null $naics_sector NAICS sector.
     *
     * @return self
     */
    public function setNaicsSector($naics_sector)
    {
        $this->container['naics_sector'] = $naics_sector;

        return $this;
    }

    /**
     * Gets naics_subsector
     *
     * @return string|null
     */
    public function getNaicsSubsector()
    {
        return $this->container['naics_subsector'];
    }

    /**
     * Sets naics_subsector
     *
     * @param string|null $naics_subsector NAICS subsector.
     *
     * @return self
     */
    public function setNaicsSubsector($naics_subsector)
    {
        $this->container['naics_subsector'] = $naics_subsector;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Company name.
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|null $phone Company phone number.
     *
     * @return self
     */
    public function setPhone($phone)
    {
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string|null $state State of company's headquarter.
     *
     * @return self
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets ticker
     *
     * @return string|null
     */
    public function getTicker()
    {
        return $this->container['ticker'];
    }

    /**
     * Sets ticker
     *
     * @param string|null $ticker Company symbol/ticker as used on the listed exchange.
     *
     * @return self
     */
    public function setTicker($ticker)
    {
        $this->container['ticker'] = $ticker;

        return $this;
    }

    /**
     * Gets weburl
     *
     * @return string|null
     */
    public function getWeburl()
    {
        return $this->container['weburl'];
    }

    /**
     * Sets weburl
     *
     * @param string|null $weburl Company website.
     *
     * @return self
     */
    public function setWeburl($weburl)
    {
        $this->container['weburl'] = $weburl;

        return $this;
    }

    /**
     * Gets ipo
     *
     * @return \DateTime|null
     */
    public function getIpo()
    {
        return $this->container['ipo'];
    }

    /**
     * Sets ipo
     *
     * @param \DateTime|null $ipo IPO date.
     *
     * @return self
     */
    public function setIpo($ipo)
    {
        $this->container['ipo'] = $ipo;

        return $this;
    }

    /**
     * Gets market_capitalization
     *
     * @return float|null
     */
    public function getMarketCapitalization()
    {
        return $this->container['market_capitalization'];
    }

    /**
     * Sets market_capitalization
     *
     * @param float|null $market_capitalization Market Capitalization.
     *
     * @return self
     */
    public function setMarketCapitalization($market_capitalization)
    {
        $this->container['market_capitalization'] = $market_capitalization;

        return $this;
    }

    /**
     * Gets share_outstanding
     *
     * @return float|null
     */
    public function getShareOutstanding()
    {
        return $this->container['share_outstanding'];
    }

    /**
     * Sets share_outstanding
     *
     * @param float|null $share_outstanding Number of oustanding shares.
     *
     * @return self
     */
    public function setShareOutstanding($share_outstanding)
    {
        $this->container['share_outstanding'] = $share_outstanding;

        return $this;
    }

    /**
     * Gets employee_total
     *
     * @return float|null
     */
    public function getEmployeeTotal()
    {
        return $this->container['employee_total'];
    }

    /**
     * Sets employee_total
     *
     * @param float|null $employee_total Number of employee.
     *
     * @return self
     */
    public function setEmployeeTotal($employee_total)
    {
        $this->container['employee_total'] = $employee_total;

        return $this;
    }

    /**
     * Gets logo
     *
     * @return string|null
     */
    public function getLogo()
    {
        return $this->container['logo'];
    }

    /**
     * Sets logo
     *
     * @param string|null $logo Logo image.
     *
     * @return self
     */
    public function setLogo($logo)
    {
        $this->container['logo'] = $logo;

        return $this;
    }

    /**
     * Gets finnhub_industry
     *
     * @return string|null
     */
    public function getFinnhubIndustry()
    {
        return $this->container['finnhub_industry'];
    }

    /**
     * Sets finnhub_industry
     *
     * @param string|null $finnhub_industry Finnhub industry classification.
     *
     * @return self
     */
    public function setFinnhubIndustry($finnhub_industry)
    {
        $this->container['finnhub_industry'] = $finnhub_industry;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


