<?php
/**
 * EarningEstimate
 *
 * PHP version 5
 *
 * @category Class
 * @package  Finnhub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Finnhub\Model;

use \ArrayAccess;
use \Finnhub\ObjectSerializer;

/**
 * EarningEstimate Class Doc Comment
 *
 * @category Class
 * @package  Finnhub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EarningEstimate implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EarningEstimate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'eps_avg' => 'float',
        'eps_high' => 'float',
        'eps_low' => 'float',
        'number_analysts' => 'int',
        'period' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'eps_avg' => 'float',
        'eps_high' => 'float',
        'eps_low' => 'float',
        'number_analysts' => 'int64',
        'period' => 'date'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'eps_avg' => 'epsAvg',
        'eps_high' => 'epsHigh',
        'eps_low' => 'epsLow',
        'number_analysts' => 'numberAnalysts',
        'period' => 'period'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'eps_avg' => 'setEpsAvg',
        'eps_high' => 'setEpsHigh',
        'eps_low' => 'setEpsLow',
        'number_analysts' => 'setNumberAnalysts',
        'period' => 'setPeriod'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'eps_avg' => 'getEpsAvg',
        'eps_high' => 'getEpsHigh',
        'eps_low' => 'getEpsLow',
        'number_analysts' => 'getNumberAnalysts',
        'period' => 'getPeriod'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['eps_avg'] = isset($data['eps_avg']) ? $data['eps_avg'] : null;
        $this->container['eps_high'] = isset($data['eps_high']) ? $data['eps_high'] : null;
        $this->container['eps_low'] = isset($data['eps_low']) ? $data['eps_low'] : null;
        $this->container['number_analysts'] = isset($data['number_analysts']) ? $data['number_analysts'] : null;
        $this->container['period'] = isset($data['period']) ? $data['period'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets eps_avg
     *
     * @return float|null
     */
    public function getEpsAvg()
    {
        return $this->container['eps_avg'];
    }

    /**
     * Sets eps_avg
     *
     * @param float|null $eps_avg Average EPS estimates.
     *
     * @return $this
     */
    public function setEpsAvg($eps_avg)
    {
        $this->container['eps_avg'] = $eps_avg;

        return $this;
    }

    /**
     * Gets eps_high
     *
     * @return float|null
     */
    public function getEpsHigh()
    {
        return $this->container['eps_high'];
    }

    /**
     * Sets eps_high
     *
     * @param float|null $eps_high Highest estimate.
     *
     * @return $this
     */
    public function setEpsHigh($eps_high)
    {
        $this->container['eps_high'] = $eps_high;

        return $this;
    }

    /**
     * Gets eps_low
     *
     * @return float|null
     */
    public function getEpsLow()
    {
        return $this->container['eps_low'];
    }

    /**
     * Sets eps_low
     *
     * @param float|null $eps_low Lowest estimate.
     *
     * @return $this
     */
    public function setEpsLow($eps_low)
    {
        $this->container['eps_low'] = $eps_low;

        return $this;
    }

    /**
     * Gets number_analysts
     *
     * @return int|null
     */
    public function getNumberAnalysts()
    {
        return $this->container['number_analysts'];
    }

    /**
     * Sets number_analysts
     *
     * @param int|null $number_analysts Number of Analysts.
     *
     * @return $this
     */
    public function setNumberAnalysts($number_analysts)
    {
        $this->container['number_analysts'] = $number_analysts;

        return $this;
    }

    /**
     * Gets period
     *
     * @return \DateTime|null
     */
    public function getPeriod()
    {
        return $this->container['period'];
    }

    /**
     * Sets period
     *
     * @param \DateTime|null $period Period.
     *
     * @return $this
     */
    public function setPeriod($period)
    {
        $this->container['period'] = $period;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


