<?php
/**
 * Estimate
 *
 * PHP version 5
 *
 * @category Class
 * @package  Finnhub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Finnhub\Model;

use \ArrayAccess;
use \Finnhub\ObjectSerializer;

/**
 * Estimate Class Doc Comment
 *
 * @category Class
 * @package  Finnhub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Estimate implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Estimate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'revenue_avg' => 'int',
        'revenue_high' => 'int',
        'revenue_low' => 'int',
        'number_analysts' => 'int',
        'period' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'revenue_avg' => 'int64',
        'revenue_high' => 'int64',
        'revenue_low' => 'int64',
        'number_analysts' => 'int64',
        'period' => 'date'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'revenue_avg' => 'revenueAvg',
        'revenue_high' => 'revenueHigh',
        'revenue_low' => 'revenueLow',
        'number_analysts' => 'numberAnalysts',
        'period' => 'period'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'revenue_avg' => 'setRevenueAvg',
        'revenue_high' => 'setRevenueHigh',
        'revenue_low' => 'setRevenueLow',
        'number_analysts' => 'setNumberAnalysts',
        'period' => 'setPeriod'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'revenue_avg' => 'getRevenueAvg',
        'revenue_high' => 'getRevenueHigh',
        'revenue_low' => 'getRevenueLow',
        'number_analysts' => 'getNumberAnalysts',
        'period' => 'getPeriod'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['revenue_avg'] = isset($data['revenue_avg']) ? $data['revenue_avg'] : null;
        $this->container['revenue_high'] = isset($data['revenue_high']) ? $data['revenue_high'] : null;
        $this->container['revenue_low'] = isset($data['revenue_low']) ? $data['revenue_low'] : null;
        $this->container['number_analysts'] = isset($data['number_analysts']) ? $data['number_analysts'] : null;
        $this->container['period'] = isset($data['period']) ? $data['period'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets revenue_avg
     *
     * @return int|null
     */
    public function getRevenueAvg()
    {
        return $this->container['revenue_avg'];
    }

    /**
     * Sets revenue_avg
     *
     * @param int|null $revenue_avg Average revenue estimates.
     *
     * @return $this
     */
    public function setRevenueAvg($revenue_avg)
    {
        $this->container['revenue_avg'] = $revenue_avg;

        return $this;
    }

    /**
     * Gets revenue_high
     *
     * @return int|null
     */
    public function getRevenueHigh()
    {
        return $this->container['revenue_high'];
    }

    /**
     * Sets revenue_high
     *
     * @param int|null $revenue_high Highest estimate.
     *
     * @return $this
     */
    public function setRevenueHigh($revenue_high)
    {
        $this->container['revenue_high'] = $revenue_high;

        return $this;
    }

    /**
     * Gets revenue_low
     *
     * @return int|null
     */
    public function getRevenueLow()
    {
        return $this->container['revenue_low'];
    }

    /**
     * Sets revenue_low
     *
     * @param int|null $revenue_low Lowest estimate.
     *
     * @return $this
     */
    public function setRevenueLow($revenue_low)
    {
        $this->container['revenue_low'] = $revenue_low;

        return $this;
    }

    /**
     * Gets number_analysts
     *
     * @return int|null
     */
    public function getNumberAnalysts()
    {
        return $this->container['number_analysts'];
    }

    /**
     * Sets number_analysts
     *
     * @param int|null $number_analysts Number of Analysts.
     *
     * @return $this
     */
    public function setNumberAnalysts($number_analysts)
    {
        $this->container['number_analysts'] = $number_analysts;

        return $this;
    }

    /**
     * Gets period
     *
     * @return \DateTime|null
     */
    public function getPeriod()
    {
        return $this->container['period'];
    }

    /**
     * Sets period
     *
     * @param \DateTime|null $period Period.
     *
     * @return $this
     */
    public function setPeriod($period)
    {
        $this->container['period'] = $period;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


