<?php
/**
 * HistoricalNBBO
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Finnhub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Finnhub\Model;

use \ArrayAccess;
use \Finnhub\ObjectSerializer;

/**
 * HistoricalNBBO Class Doc Comment
 *
 * @category Class
 * @package  Finnhub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class HistoricalNBBO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'HistoricalNBBO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        's' => 'string',
        'skip' => 'int',
        'count' => 'int',
        'total' => 'int',
        'av' => 'float[]',
        'a' => 'float[]',
        'ax' => 'string[]',
        'bv' => 'float[]',
        'b' => 'float[]',
        'bx' => 'string[]',
        't' => 'int[]',
        'c' => 'string[][]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        's' => null,
        'skip' => 'int64',
        'count' => 'int64',
        'total' => 'int64',
        'av' => 'float',
        'a' => 'float',
        'ax' => null,
        'bv' => 'float',
        'b' => 'float',
        'bx' => null,
        't' => 'int64',
        'c' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        's' => 's',
        'skip' => 'skip',
        'count' => 'count',
        'total' => 'total',
        'av' => 'av',
        'a' => 'a',
        'ax' => 'ax',
        'bv' => 'bv',
        'b' => 'b',
        'bx' => 'bx',
        't' => 't',
        'c' => 'c'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        's' => 'setS',
        'skip' => 'setSkip',
        'count' => 'setCount',
        'total' => 'setTotal',
        'av' => 'setAv',
        'a' => 'setA',
        'ax' => 'setAx',
        'bv' => 'setBv',
        'b' => 'setB',
        'bx' => 'setBx',
        't' => 'setT',
        'c' => 'setC'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        's' => 'getS',
        'skip' => 'getSkip',
        'count' => 'getCount',
        'total' => 'getTotal',
        'av' => 'getAv',
        'a' => 'getA',
        'ax' => 'getAx',
        'bv' => 'getBv',
        'b' => 'getB',
        'bx' => 'getBx',
        't' => 'getT',
        'c' => 'getC'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['s'] = $data['s'] ?? null;
        $this->container['skip'] = $data['skip'] ?? null;
        $this->container['count'] = $data['count'] ?? null;
        $this->container['total'] = $data['total'] ?? null;
        $this->container['av'] = $data['av'] ?? null;
        $this->container['a'] = $data['a'] ?? null;
        $this->container['ax'] = $data['ax'] ?? null;
        $this->container['bv'] = $data['bv'] ?? null;
        $this->container['b'] = $data['b'] ?? null;
        $this->container['bx'] = $data['bx'] ?? null;
        $this->container['t'] = $data['t'] ?? null;
        $this->container['c'] = $data['c'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets s
     *
     * @return string|null
     */
    public function getS()
    {
        return $this->container['s'];
    }

    /**
     * Sets s
     *
     * @param string|null $s Symbol.
     *
     * @return self
     */
    public function setS($s)
    {
        $this->container['s'] = $s;

        return $this;
    }

    /**
     * Gets skip
     *
     * @return int|null
     */
    public function getSkip()
    {
        return $this->container['skip'];
    }

    /**
     * Sets skip
     *
     * @param int|null $skip Number of ticks skipped.
     *
     * @return self
     */
    public function setSkip($skip)
    {
        $this->container['skip'] = $skip;

        return $this;
    }

    /**
     * Gets count
     *
     * @return int|null
     */
    public function getCount()
    {
        return $this->container['count'];
    }

    /**
     * Sets count
     *
     * @param int|null $count Number of ticks returned. If <code>count</code> < <code>limit</code>, all data for that date has been returned.
     *
     * @return self
     */
    public function setCount($count)
    {
        $this->container['count'] = $count;

        return $this;
    }

    /**
     * Gets total
     *
     * @return int|null
     */
    public function getTotal()
    {
        return $this->container['total'];
    }

    /**
     * Sets total
     *
     * @param int|null $total Total number of ticks for that date.
     *
     * @return self
     */
    public function setTotal($total)
    {
        $this->container['total'] = $total;

        return $this;
    }

    /**
     * Gets av
     *
     * @return float[]|null
     */
    public function getAv()
    {
        return $this->container['av'];
    }

    /**
     * Sets av
     *
     * @param float[]|null $av List of Ask volume data.
     *
     * @return self
     */
    public function setAv($av)
    {
        $this->container['av'] = $av;

        return $this;
    }

    /**
     * Gets a
     *
     * @return float[]|null
     */
    public function getA()
    {
        return $this->container['a'];
    }

    /**
     * Sets a
     *
     * @param float[]|null $a List of Ask price data.
     *
     * @return self
     */
    public function setA($a)
    {
        $this->container['a'] = $a;

        return $this;
    }

    /**
     * Gets ax
     *
     * @return string[]|null
     */
    public function getAx()
    {
        return $this->container['ax'];
    }

    /**
     * Sets ax
     *
     * @param string[]|null $ax List of venues/exchanges - Ask price. A list of exchange codes can be found <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1Tj53M1svmr-hfEtbk6_NpVR1yAyGLMaH6ByYU6CG0ZY/edit?usp=sharing\",>here</a>
     *
     * @return self
     */
    public function setAx($ax)
    {
        $this->container['ax'] = $ax;

        return $this;
    }

    /**
     * Gets bv
     *
     * @return float[]|null
     */
    public function getBv()
    {
        return $this->container['bv'];
    }

    /**
     * Sets bv
     *
     * @param float[]|null $bv List of Bid volume data.
     *
     * @return self
     */
    public function setBv($bv)
    {
        $this->container['bv'] = $bv;

        return $this;
    }

    /**
     * Gets b
     *
     * @return float[]|null
     */
    public function getB()
    {
        return $this->container['b'];
    }

    /**
     * Sets b
     *
     * @param float[]|null $b List of Bid price data.
     *
     * @return self
     */
    public function setB($b)
    {
        $this->container['b'] = $b;

        return $this;
    }

    /**
     * Gets bx
     *
     * @return string[]|null
     */
    public function getBx()
    {
        return $this->container['bx'];
    }

    /**
     * Sets bx
     *
     * @param string[]|null $bx List of venues/exchanges - Bid price. A list of exchange codes can be found <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1Tj53M1svmr-hfEtbk6_NpVR1yAyGLMaH6ByYU6CG0ZY/edit?usp=sharing\",>here</a>
     *
     * @return self
     */
    public function setBx($bx)
    {
        $this->container['bx'] = $bx;

        return $this;
    }

    /**
     * Gets t
     *
     * @return int[]|null
     */
    public function getT()
    {
        return $this->container['t'];
    }

    /**
     * Sets t
     *
     * @param int[]|null $t List of timestamp in UNIX ms.
     *
     * @return self
     */
    public function setT($t)
    {
        $this->container['t'] = $t;

        return $this;
    }

    /**
     * Gets c
     *
     * @return string[][]|null
     */
    public function getC()
    {
        return $this->container['c'];
    }

    /**
     * Sets c
     *
     * @param string[][]|null $c List of quote conditions. A comprehensive list of quote conditions code can be found <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1iiA6e7Osdtai0oPMOUzgAIKXCsay89dFDmsegz6OpEg/edit?usp=sharing\">here</a>
     *
     * @return self
     */
    public function setC($c)
    {
        $this->container['c'] = $c;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


