<?php
/**
 * UsaSpending
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Finnhub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Finnhub\Model;

use \ArrayAccess;
use \Finnhub\ObjectSerializer;

/**
 * UsaSpending Class Doc Comment
 *
 * @category Class
 * @package  Finnhub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class UsaSpending implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'UsaSpending';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'symbol' => 'string',
        'recipient_name' => 'string',
        'recipient_parent_name' => 'string',
        'award_description' => 'string',
        'country' => 'string',
        'action_date' => 'string',
        'total_value' => 'float',
        'performance_start_date' => 'string',
        'performance_end_date' => 'string',
        'awarding_agency_name' => 'string',
        'awarding_sub_agency_name' => 'string',
        'awarding_office_name' => 'string',
        'performance_country' => 'string',
        'performance_city' => 'string',
        'performance_county' => 'string',
        'performance_state' => 'string',
        'performance_zip_code' => 'string',
        'performance_congressional_district' => 'string',
        'naics_code' => 'string',
        'permalink' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'symbol' => null,
        'recipient_name' => null,
        'recipient_parent_name' => null,
        'award_description' => null,
        'country' => null,
        'action_date' => null,
        'total_value' => 'float',
        'performance_start_date' => null,
        'performance_end_date' => null,
        'awarding_agency_name' => null,
        'awarding_sub_agency_name' => null,
        'awarding_office_name' => null,
        'performance_country' => null,
        'performance_city' => null,
        'performance_county' => null,
        'performance_state' => null,
        'performance_zip_code' => null,
        'performance_congressional_district' => null,
        'naics_code' => null,
        'permalink' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'symbol' => 'symbol',
        'recipient_name' => 'recipientName',
        'recipient_parent_name' => 'recipientParentName',
        'award_description' => 'awardDescription',
        'country' => 'country',
        'action_date' => 'actionDate',
        'total_value' => 'totalValue',
        'performance_start_date' => 'performanceStartDate',
        'performance_end_date' => 'performanceEndDate',
        'awarding_agency_name' => 'awardingAgencyName',
        'awarding_sub_agency_name' => 'awardingSubAgencyName',
        'awarding_office_name' => 'awardingOfficeName',
        'performance_country' => 'performanceCountry',
        'performance_city' => 'performanceCity',
        'performance_county' => 'performanceCounty',
        'performance_state' => 'performanceState',
        'performance_zip_code' => 'performanceZipCode',
        'performance_congressional_district' => 'performanceCongressionalDistrict',
        'naics_code' => 'naicsCode',
        'permalink' => 'permalink'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'symbol' => 'setSymbol',
        'recipient_name' => 'setRecipientName',
        'recipient_parent_name' => 'setRecipientParentName',
        'award_description' => 'setAwardDescription',
        'country' => 'setCountry',
        'action_date' => 'setActionDate',
        'total_value' => 'setTotalValue',
        'performance_start_date' => 'setPerformanceStartDate',
        'performance_end_date' => 'setPerformanceEndDate',
        'awarding_agency_name' => 'setAwardingAgencyName',
        'awarding_sub_agency_name' => 'setAwardingSubAgencyName',
        'awarding_office_name' => 'setAwardingOfficeName',
        'performance_country' => 'setPerformanceCountry',
        'performance_city' => 'setPerformanceCity',
        'performance_county' => 'setPerformanceCounty',
        'performance_state' => 'setPerformanceState',
        'performance_zip_code' => 'setPerformanceZipCode',
        'performance_congressional_district' => 'setPerformanceCongressionalDistrict',
        'naics_code' => 'setNaicsCode',
        'permalink' => 'setPermalink'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'symbol' => 'getSymbol',
        'recipient_name' => 'getRecipientName',
        'recipient_parent_name' => 'getRecipientParentName',
        'award_description' => 'getAwardDescription',
        'country' => 'getCountry',
        'action_date' => 'getActionDate',
        'total_value' => 'getTotalValue',
        'performance_start_date' => 'getPerformanceStartDate',
        'performance_end_date' => 'getPerformanceEndDate',
        'awarding_agency_name' => 'getAwardingAgencyName',
        'awarding_sub_agency_name' => 'getAwardingSubAgencyName',
        'awarding_office_name' => 'getAwardingOfficeName',
        'performance_country' => 'getPerformanceCountry',
        'performance_city' => 'getPerformanceCity',
        'performance_county' => 'getPerformanceCounty',
        'performance_state' => 'getPerformanceState',
        'performance_zip_code' => 'getPerformanceZipCode',
        'performance_congressional_district' => 'getPerformanceCongressionalDistrict',
        'naics_code' => 'getNaicsCode',
        'permalink' => 'getPermalink'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['symbol'] = $data['symbol'] ?? null;
        $this->container['recipient_name'] = $data['recipient_name'] ?? null;
        $this->container['recipient_parent_name'] = $data['recipient_parent_name'] ?? null;
        $this->container['award_description'] = $data['award_description'] ?? null;
        $this->container['country'] = $data['country'] ?? null;
        $this->container['action_date'] = $data['action_date'] ?? null;
        $this->container['total_value'] = $data['total_value'] ?? null;
        $this->container['performance_start_date'] = $data['performance_start_date'] ?? null;
        $this->container['performance_end_date'] = $data['performance_end_date'] ?? null;
        $this->container['awarding_agency_name'] = $data['awarding_agency_name'] ?? null;
        $this->container['awarding_sub_agency_name'] = $data['awarding_sub_agency_name'] ?? null;
        $this->container['awarding_office_name'] = $data['awarding_office_name'] ?? null;
        $this->container['performance_country'] = $data['performance_country'] ?? null;
        $this->container['performance_city'] = $data['performance_city'] ?? null;
        $this->container['performance_county'] = $data['performance_county'] ?? null;
        $this->container['performance_state'] = $data['performance_state'] ?? null;
        $this->container['performance_zip_code'] = $data['performance_zip_code'] ?? null;
        $this->container['performance_congressional_district'] = $data['performance_congressional_district'] ?? null;
        $this->container['naics_code'] = $data['naics_code'] ?? null;
        $this->container['permalink'] = $data['permalink'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets symbol
     *
     * @return string|null
     */
    public function getSymbol()
    {
        return $this->container['symbol'];
    }

    /**
     * Sets symbol
     *
     * @param string|null $symbol Symbol.
     *
     * @return self
     */
    public function setSymbol($symbol)
    {
        $this->container['symbol'] = $symbol;

        return $this;
    }

    /**
     * Gets recipient_name
     *
     * @return string|null
     */
    public function getRecipientName()
    {
        return $this->container['recipient_name'];
    }

    /**
     * Sets recipient_name
     *
     * @param string|null $recipient_name Company's name.
     *
     * @return self
     */
    public function setRecipientName($recipient_name)
    {
        $this->container['recipient_name'] = $recipient_name;

        return $this;
    }

    /**
     * Gets recipient_parent_name
     *
     * @return string|null
     */
    public function getRecipientParentName()
    {
        return $this->container['recipient_parent_name'];
    }

    /**
     * Sets recipient_parent_name
     *
     * @param string|null $recipient_parent_name Company's name.
     *
     * @return self
     */
    public function setRecipientParentName($recipient_parent_name)
    {
        $this->container['recipient_parent_name'] = $recipient_parent_name;

        return $this;
    }

    /**
     * Gets award_description
     *
     * @return string|null
     */
    public function getAwardDescription()
    {
        return $this->container['award_description'];
    }

    /**
     * Sets award_description
     *
     * @param string|null $award_description Description.
     *
     * @return self
     */
    public function setAwardDescription($award_description)
    {
        $this->container['award_description'] = $award_description;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country Recipient's country.
     *
     * @return self
     */
    public function setCountry($country)
    {
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets action_date
     *
     * @return string|null
     */
    public function getActionDate()
    {
        return $this->container['action_date'];
    }

    /**
     * Sets action_date
     *
     * @param string|null $action_date Period.
     *
     * @return self
     */
    public function setActionDate($action_date)
    {
        $this->container['action_date'] = $action_date;

        return $this;
    }

    /**
     * Gets total_value
     *
     * @return float|null
     */
    public function getTotalValue()
    {
        return $this->container['total_value'];
    }

    /**
     * Sets total_value
     *
     * @param float|null $total_value Income reported by lobbying firms.
     *
     * @return self
     */
    public function setTotalValue($total_value)
    {
        $this->container['total_value'] = $total_value;

        return $this;
    }

    /**
     * Gets performance_start_date
     *
     * @return string|null
     */
    public function getPerformanceStartDate()
    {
        return $this->container['performance_start_date'];
    }

    /**
     * Sets performance_start_date
     *
     * @param string|null $performance_start_date Performance start date.
     *
     * @return self
     */
    public function setPerformanceStartDate($performance_start_date)
    {
        $this->container['performance_start_date'] = $performance_start_date;

        return $this;
    }

    /**
     * Gets performance_end_date
     *
     * @return string|null
     */
    public function getPerformanceEndDate()
    {
        return $this->container['performance_end_date'];
    }

    /**
     * Sets performance_end_date
     *
     * @param string|null $performance_end_date Performance end date.
     *
     * @return self
     */
    public function setPerformanceEndDate($performance_end_date)
    {
        $this->container['performance_end_date'] = $performance_end_date;

        return $this;
    }

    /**
     * Gets awarding_agency_name
     *
     * @return string|null
     */
    public function getAwardingAgencyName()
    {
        return $this->container['awarding_agency_name'];
    }

    /**
     * Sets awarding_agency_name
     *
     * @param string|null $awarding_agency_name Award agency.
     *
     * @return self
     */
    public function setAwardingAgencyName($awarding_agency_name)
    {
        $this->container['awarding_agency_name'] = $awarding_agency_name;

        return $this;
    }

    /**
     * Gets awarding_sub_agency_name
     *
     * @return string|null
     */
    public function getAwardingSubAgencyName()
    {
        return $this->container['awarding_sub_agency_name'];
    }

    /**
     * Sets awarding_sub_agency_name
     *
     * @param string|null $awarding_sub_agency_name Award sub-agency.
     *
     * @return self
     */
    public function setAwardingSubAgencyName($awarding_sub_agency_name)
    {
        $this->container['awarding_sub_agency_name'] = $awarding_sub_agency_name;

        return $this;
    }

    /**
     * Gets awarding_office_name
     *
     * @return string|null
     */
    public function getAwardingOfficeName()
    {
        return $this->container['awarding_office_name'];
    }

    /**
     * Sets awarding_office_name
     *
     * @param string|null $awarding_office_name Award office name.
     *
     * @return self
     */
    public function setAwardingOfficeName($awarding_office_name)
    {
        $this->container['awarding_office_name'] = $awarding_office_name;

        return $this;
    }

    /**
     * Gets performance_country
     *
     * @return string|null
     */
    public function getPerformanceCountry()
    {
        return $this->container['performance_country'];
    }

    /**
     * Sets performance_country
     *
     * @param string|null $performance_country Performance country.
     *
     * @return self
     */
    public function setPerformanceCountry($performance_country)
    {
        $this->container['performance_country'] = $performance_country;

        return $this;
    }

    /**
     * Gets performance_city
     *
     * @return string|null
     */
    public function getPerformanceCity()
    {
        return $this->container['performance_city'];
    }

    /**
     * Sets performance_city
     *
     * @param string|null $performance_city Performance city.
     *
     * @return self
     */
    public function setPerformanceCity($performance_city)
    {
        $this->container['performance_city'] = $performance_city;

        return $this;
    }

    /**
     * Gets performance_county
     *
     * @return string|null
     */
    public function getPerformanceCounty()
    {
        return $this->container['performance_county'];
    }

    /**
     * Sets performance_county
     *
     * @param string|null $performance_county Performance county.
     *
     * @return self
     */
    public function setPerformanceCounty($performance_county)
    {
        $this->container['performance_county'] = $performance_county;

        return $this;
    }

    /**
     * Gets performance_state
     *
     * @return string|null
     */
    public function getPerformanceState()
    {
        return $this->container['performance_state'];
    }

    /**
     * Sets performance_state
     *
     * @param string|null $performance_state Performance state.
     *
     * @return self
     */
    public function setPerformanceState($performance_state)
    {
        $this->container['performance_state'] = $performance_state;

        return $this;
    }

    /**
     * Gets performance_zip_code
     *
     * @return string|null
     */
    public function getPerformanceZipCode()
    {
        return $this->container['performance_zip_code'];
    }

    /**
     * Sets performance_zip_code
     *
     * @param string|null $performance_zip_code Performance zip code.
     *
     * @return self
     */
    public function setPerformanceZipCode($performance_zip_code)
    {
        $this->container['performance_zip_code'] = $performance_zip_code;

        return $this;
    }

    /**
     * Gets performance_congressional_district
     *
     * @return string|null
     */
    public function getPerformanceCongressionalDistrict()
    {
        return $this->container['performance_congressional_district'];
    }

    /**
     * Sets performance_congressional_district
     *
     * @param string|null $performance_congressional_district Performance congressional district.
     *
     * @return self
     */
    public function setPerformanceCongressionalDistrict($performance_congressional_district)
    {
        $this->container['performance_congressional_district'] = $performance_congressional_district;

        return $this;
    }

    /**
     * Gets naics_code
     *
     * @return string|null
     */
    public function getNaicsCode()
    {
        return $this->container['naics_code'];
    }

    /**
     * Sets naics_code
     *
     * @param string|null $naics_code NAICS code.
     *
     * @return self
     */
    public function setNaicsCode($naics_code)
    {
        $this->container['naics_code'] = $naics_code;

        return $this;
    }

    /**
     * Gets permalink
     *
     * @return string|null
     */
    public function getPermalink()
    {
        return $this->container['permalink'];
    }

    /**
     * Sets permalink
     *
     * @param string|null $permalink Permalink.
     *
     * @return self
     */
    public function setPermalink($permalink)
    {
        $this->container['permalink'] = $permalink;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


