<?php
/**
 * DividendsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Finnhub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Finnhub;

use PHPUnit\Framework\TestCase;

/**
 * DividendsTest Class Doc Comment
 *
 * @category    Class
 * @description Dividends
 * @package     Finnhub
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DividendsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Dividends"
     */
    public function testDividends()
    {
    }

    /**
     * Test attribute "symbol"
     */
    public function testPropertySymbol()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "adjusted_amount"
     */
    public function testPropertyAdjustedAmount()
    {
    }

    /**
     * Test attribute "pay_date"
     */
    public function testPropertyPayDate()
    {
    }

    /**
     * Test attribute "record_date"
     */
    public function testPropertyRecordDate()
    {
    }

    /**
     * Test attribute "declaration_date"
     */
    public function testPropertyDeclarationDate()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }
}
