<?php
/**
 * FilingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Finnhub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Finnhub;

use PHPUnit\Framework\TestCase;

/**
 * FilingTest Class Doc Comment
 *
 * @category    Class
 * @description Filing
 * @package     Finnhub
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FilingTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Filing"
     */
    public function testFiling()
    {
    }

    /**
     * Test attribute "access_number"
     */
    public function testPropertyAccessNumber()
    {
    }

    /**
     * Test attribute "symbol"
     */
    public function testPropertySymbol()
    {
    }

    /**
     * Test attribute "cik"
     */
    public function testPropertyCik()
    {
    }

    /**
     * Test attribute "form"
     */
    public function testPropertyForm()
    {
    }

    /**
     * Test attribute "filed_date"
     */
    public function testPropertyFiledDate()
    {
    }

    /**
     * Test attribute "accepted_date"
     */
    public function testPropertyAcceptedDate()
    {
    }

    /**
     * Test attribute "report_url"
     */
    public function testPropertyReportUrl()
    {
    }

    /**
     * Test attribute "filing_url"
     */
    public function testPropertyFilingUrl()
    {
    }
}
