<?php
/**
 * IsinChangeInfoTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Finnhub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Finnhub\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * IsinChangeInfoTest Class Doc Comment
 *
 * @category    Class
 * @description IsinChangeInfo
 * @package     Finnhub
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class IsinChangeInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "IsinChangeInfo"
     */
    public function testIsinChangeInfo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "at_date"
     */
    public function testPropertyAtDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "old_isin"
     */
    public function testPropertyOldIsin()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "new_isin"
     */
    public function testPropertyNewIsin()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
